# Install task `brew install go-task/tap/go-task`
# https://github.com/go-task/task
# https://taskfile.dev

version: '2'

env:
  CGO_ENABLED: "0"
  GOPROXY: "https://goproxy.cn,https://goproxy.io"
  GO111MODULE: "on"

vars:
  GIT_COMMIT:
    sh: git describe --tags --always --long

tasks:
  proto:
    cmds:
      - prototool all
    dir: proto

  build:
    cmds:
      - go build -ldflags "-X 'github.com/qiuyuzhou/h2tun/cmd/h2tun/cmd.version={{.GIT_COMMIT}}'" -o ./h2tun ./cmd/h2tun

  clean:
    cmds:
      - rm -f ./h2tun


